<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Ejetor_de_cartao</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>cards_outline_icon_139050 (1).ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="cards_outline_icon_139050 (1).ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Ports" Version="10.0.2" />
  </ItemGroup>

</Project>
